services:
  mysql:
    image: mysql:8.0
    container_name: banking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SistemaBancarioDb
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password